# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6f9e9f8465efd9874132dc280a4c99cb9aa3d76ce3cc8893618d9056d7d5be8a106184dcdccb54adaa040edd93d56f8e8f1ffa359c1729b7fbe9601e1a43c0

test:
  secret_key_base: 73acfa4652db964922ca89850d5baefa40ee5446a0b2fc742351decd9ea579a79d0917dabd6deeb6e3e3ff36d32becccfa466c5c36ab6e686ab276a00420015f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
