# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0be9d42a858d704a0b67c32e9cb6ab9cbe4c3ca50921b2deb8a34827716606e680860636ac165ca2a6d80d4d06ac97797150cbf4dd22195a716ef0ce922ab3f

test:
  secret_key_base: 700973ef2691dbefd2d38db97157f55a28eda048c546daf0f1c0d0ccfca2c61d7d7ac83e2f2f1ddcbac1182f7d9c2779c9cb737efcb1fdd8f13a3bc67fa33106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 57e737af90c7c1a6a03b217b3601141ab887d3a9cd7f8f71ab193a0bca89cd5de1ce989d55e39d95a03bde6707159aad648d66f02da3974dc91eaae4d8868839
