# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58fa868ae644a4ce8560ab900da5388773f6a2923f3b6716ac2452bee6ee0f31082b5b02bf03cf30fdaef137e08d9a50242e6a4628c0dc5efb441c6a8f7482c7

test:
  secret_key_base: 10751fd51469edeb89ac67a4b209252bd67fab1431ebc78a250add36edc63bc6212d06c9f8bef5d50c9c1f3fbcd9a68f36ff524019dff30e8ae08fddf1952c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
