# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbca444c6adf2a009a9542f6c9488fec55207a6a1f1d82c4632c1b6f20d26449f682d9f1cb0cebd04cb01f87be7a8d7657fe166759f0190f9d4fe548b6a2abd

test:
  secret_key_base: 4afc316881c413ca6f78ee5cc93422120d1aeb1d25b062555723b3731d55d8b72d20fac45385b5bf9bdec686e8d448e1ecf1a638edfdf37611dc8dc5b972a08d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
